# # This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# # For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

# name: Node.js Package

# on:
#   release:
#     types: [created]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#       - run: npm ci
#       - run: npm test

#   publish-gpr:
#     needs: build
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20.16.0
#           registry-url: https://npm.pkg.github.com/
#       - run: npm ci
#       - run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
#       - name: Deploy with gh-pages
#         run: |
#           git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
#           npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



# name: Deploy React App to GitHub Pages

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  # Force Node.js 20 usage

#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v3  # Use v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v3  # Use Node.js 20
#         with:
#           node-version: '20'

#       - name: Install dependencies
#         run: npm install

#       - name: Build the React app
#         run: npm run build

#       - name: Deploy to GitHub Pages
#         run: npm run deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main
      
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
  

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
